version: '3'

networks:
    monitoring:
        driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
    prometheus:
        image: prom/prometheus:v2.32.1
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        ports:
            - '9090:9090'
        expose:
            - 9090
        networks:
            - monitoring
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        ports:
            - '3001:3001'
        expose:
            - 3001
        networks:
            - monitoring
    redis:
        image: redis:6.2-alpine
        ports:
            - '${REDIS_PORT:-6379}:6379'
        networks:
            - monitoring
    server:
        build: .
        volumes:
            - .:/usr/src/app
        # image: lukerhoads/traderjoe_api:latest
        environment:
            - NODE_ENV="${NODE_ENV}"
            - NETWORK="${NETWORK}"
            - HOST="${HOST}"
            - PORT="${PORT}"
            - REDIS_HOST="${REDIS_HOST}"
            - REDIS_PORT="${REDIS_PORT}"
        ports:
            - '3000:3000'
        expose:
            - 3000
        depends_on:
            - redis
        networks:
            - monitoring
        # deploy:
        #   mode: replicated
        #   replicas: 3
