version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus 
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090 
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:v8.2.6
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana 
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports: 
      - 3001:3001
    expose:
      - 3001
    networks: 
      - monitoring
  redis:
    image: redis 
    ports:
      - '${REDIS_PORT:-6379}:6379'
  server:
    image: lukerhoads/traderjoe_api:latest
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - redis
    # deploy:
    #   mode: replicated
    #   replicas: 3
