openapi: 3.0.0
info:
  title: TraderJoe API
  description: Easily retrieve info on the state of Trader Joe.
  version: 0.0.1
basePath: /v1

servers:
  - url: https://api.traderjoexyz.com/v1
    description: Production

paths:
  /ping:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: Pong
  # /supply:
  # /price:
  # /nft:
  # /metrics:
  
components:
  schemas:
    address: 
      type: string
      example: 0xb794f5ea0ba39494ce839613fffba74279579268
    status:
      type: object
      properties:
        timestamp: 
          type: string
        error_code:
          type: integer
        error_message:
          type: string
  securitySchemes: